// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipzirjdmwbhkseojukbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwemlyamRtd2Joa3Nlb2p1a2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTE2NzksImV4cCI6MjA1ODU4NzY3OX0.QLZN0vKju3sYIi-i0cHjatV9KXDZPH43eSyAiFD-OQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);